"""add calculation sex to profiles

Revision ID: 7f0dd66dde23
Revises: 0d5ad501ac11
Create Date: 2026-08-31 23:24:50.885243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0dd66dde23'
down_revision: Union[str, Sequence[str], None] = '0d5ad501ac11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('calculation_sex', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'calculation_sex')
    # ### end Alembic commands ###
